services:
  app:
    build: .
    ports:
      - "8080:8080"
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservice_test_db
  resilience4j:
    circuitbreaker:
      configs:
        default:
          registerHealthIndicator: true
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 10000
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
      instances:
        myService:
          baseConfig: default